### ISSUE TITLE
Mark up IT ISO documents

### ISSUE THREAD

**Issue by opoudjis** [riboseinc/metanorma-iso#12]
To find examples of source code etc, and how it is rendered. @ronaldtse, any drafts or completed standards I should look at?

**Comment by ronaldtse** [comment]
There are plenty in public indeed!

The ISO maintains the following PAS list: http://standards.iso.org/ittf/PubliclyAvailableStandards/index.html

The following documents are useful in their properties:

* ISO/IEC 27000: InfoSec terms - very long terms of reference
* ISO/IEC 29100: PII - privacy principles
* ISO/IEC 40314: MathML - code, tables, math
* ISO/IEC 21778:2017: JSON - a minimal standard example




ISO/IEC 21778:2017 |  
-- | --


ISO/IEC 21778:2017 |  
-- | --

**Comment by ronaldtse** [comment]
"ISO/IEC 40314: MathML" has a lot of source code in there. However this document has a very non-standard textual formatting. It actually looks like it's been typeset in LaTeX. Hence the importance of a standardized document model.

**Comment by ronaldtse** [comment]
@opoudjis Let's markup the JSON document, simple, easy and free.

**Comment by opoudjis** [comment]
This will speed up once we have reverse_asciidoctor implemented.

**Comment by ronaldtse** [comment]
Or unless, this is purely for demonstration purposes. That could be nice and useful.

**Comment by opoudjis** [comment]
... We already have the Rice document for demonstration purposes. I think we can let this go, so long as you keep finding new documents to encode...
