### ISSUE TITLE
Render TODO as annotation

### ISSUE THREAD

**Issue by opoudjis** [riboseinc/metanorma-iso#148]

**Comment by ronaldtse** [comment]
@opoudjis It sounds correct to render them annotations. However, in HTML can we have a way to display them inline?

**Comment by opoudjis** [comment]
As an interim solution because https://github.com/riboseinc/isodoc-style/issues/3 isn't getting done, or as a long-term solution?

**Comment by ronaldtse** [comment]
I think the key point here is to embed the TODOs in the XML as semantic elements.

https://github.com/riboseinc/isodoc-style/issues/3 relates to the HTML output of these annotations?

**Comment by opoudjis** [comment]
Yes

**Comment by opoudjis** [comment]
TODO statements are not in fact natively recognised by Asciidoctor, even though my syntax highlighter does. Forcing Asciidoctor to recognise them seems not a good use of time, will review whether there is precedent for them being used in Asciidoctor at all.

**Comment by opoudjis** [comment]
No support currently in Asciidoctor for TODO blocks as a kind of distinct admonition: https://github.com/asciidoctor/asciidoctor/issues/1692

Since they are not natively part of Asciidoctor, I have to ask whether we should support them at all. I can grab any paragraph which starts with `TODO:` and treat it as a reviewer comment; I'm just not convinced I should. @ronaldtse?

**Comment by ronaldtse** [comment]
We don't quite care about sticking to "Asciidoctor syntax"; it's just a parser to us. It would be great if we can parse those as comments.

**Comment by opoudjis** [comment]
Implemented. They are being rendered as reviewer comments; https://github.com/riboseinc/isodoc-style/issues/3 will need to be implemented for them to be displayed in HTML. But reviewer comment, not straight comments, are the right way to process these.
