### ISSUE TITLE
Review and update Gem Customisation Guide

### ISSUE THREAD

**Issue by opoudjis** [riboseinc/metanorma-iso#176]
https://github.com/riboseinc/asciidoctor-iso/wiki/Gem-Customisation-Guide

@ronaldtse to review.
@opoudjis to update class names to reflect recent IsoDoc refactoring, and to mention registering with Metanorma.

**Comment by ronaldtse** [comment]
@opoudjis the guide is very well written, impressive 👍 

* The `Convert` class name is now `HtmlConvert`
* Some programmatic syntax should be wrapped with back-ticks (e.g. "IsoDoc::...::WordConvert")
* We should further enrich this guide into a "how-to" -- a step by step demonstration how to create a new ("fictitious") gem with minor modifications (shown in code snippets).

**Comment by ronaldtse** [comment]
Actually makes me wonder if we should actually wrap each standard adaptation in a `metanorma-iso` gem instead of wrapping them (asciidoctor and isodoc components) in `asciidoctor-iso`? Or is it better to further separate them into `asciidoctor-iso` and `isodoc-iso`?

**Comment by opoudjis** [comment]
Done these:

* The Convert class name is now HtmlConvert
* Some programmatic syntax should be wrapped with back-ticks (e.g. "IsoDoc::...::WordConvert")

Can I use the existing rsd gem to demonstrate the How-To, rather than doing it from scratch?

Renaming the gem from asciidoctor-iso to metanorma-iso would be ok to me, with different input classes all located under the one gem: metanorma-iso/lib/asciidoctor, metanorma-iso/lib/markdown,  metanorma-iso/lib/selagraph, metanorma-iso/lib/isodoc. Of course, we're now using metanorma-iso for something else, and would need to rename it metanorma-model-iso.

**Comment by ronaldtse** [comment]
Agree with all. Except that with using the RSD gem to demonstrate the How-To -- maybe there should be a more "stable" version since we (I) may break it with enhancements for our own internal usage. I'd hate to have the responsibility of that 😉

**Comment by ronaldtse** [comment]
@opoudjis I've renamed the `metanorma-model-*` repos, but maybe it would be better to separate these three things?

1. input to model: (asciidoctor-iso)
2. model and its serialization: (isodoc-iso)
3. isodoc to rendered output: (_no name yet?_)

**Comment by opoudjis** [comment]
I'll clone asciidoctor-rsd to asciidoctor-sample

My objections to separating out the classes into separate gems remain. This is already a maintenance nightmare, and I will not accept it becoming a nightmare x 3.

**Comment by ronaldtse** [comment]
Agree, it's a pain. let's keep them together in `metanorma-*` for now. When the need comes we can still split them since they have separate namespaces.

The point remains that we should have three different components in a `metanorma-*` gem, and they should use separate namespaces. These three types of components should each be based off a common "base" class in the `metanorma` gem (maybe we call them e.g., `metanorma/compiler`, `metanorma/isodoc`, `metanorma/renderer`.

**Comment by ronaldtse** [comment]
And the `metanorma-sample-standard` gem (which includes `asciidoctor-sample`) should also include classes based off `metanorma/compiler`, `metanorma/isodoc`, `metanorma/renderer`.

**Comment by opoudjis** [comment]
I do not understand where there are three components.

* metanorma/compiler corresponds to asciidoctor-gb/lib/asciidoctor, inputs Asciidoc, and outputs isodoc xml
* metanorma/renderer corresponds to asciidoctor-gb/lib/asciidoctor/isodoc, inputs isodoc xml, and outputs HTML
* .... what is the model and its serialisation in the gem? The RNG grammars?  The existing stuff in metanorma-model-*? Whatever it is, calling it metanorma/isodoc is misleading; just call it metanorma/model.

**Comment by ronaldtse** [comment]
> what is the model and its serialisation in the gem

This is the "isodoc" gem where it is used to create the isodoc XML, manipulate it, and save it.

**Comment by opoudjis** [comment]
The Metanorma class has been documented.

**Comment by opoudjis** [comment]
This ticket's remaining task is:

> We should further enrich this guide into a "how-to" -- a step by step demonstration how to create a new ("fictitious") gem with minor modifications (shown in code snippets).

They will be appended to each section, using the sample gem as a basis for customisation.

**Comment by opoudjis** [comment]
Done
