### ISSUE TITLE
Rename to metanorma-iso

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/metanorma-iso#194]
We're getting adoption so it's probably a good time to rename our gems according to the new `metanorma-*` convention.

**Comment by opoudjis** [comment]
Applies to all gems

**Comment by opoudjis** [comment]
Done, with a couple of false starts. Updated metanorma-cli as well.

Taken the opportunity to shift  metanorma-csd, metanorma-csand, metanorma-m3d, metanorma-rsd, metanorma-acme, metanorma-sample to be subclasses of metanorma-standoc and not metanorma-iso. metanorma-gb remains a subclass of metanorma-iso, given their close alignment.
