### ISSUE TITLE
Encode ISO 8601-1 in Metanorma

### ISSUE THREAD

**Issue by opoudjis** [riboseinc/metanorma-iso#199]

**Comment by opoudjis** [comment]
You have a term note containing an unordered list; this is illegal according to our grammar, which allows only single paragraphs under term notes, and no other block types:

````
[NOTE]
====
A time scale may amongst others be chosen as:

* continuous, e.g. international atomic time (TAI) (see <<IEV,clause "713-05-18">>);
* continuous with discontinuities, e.g. _Coordinated Universal Time (UTC)_ (<<term-utc>>) due to leap seconds, standard time due to summer time and winter time;
* successive steps, e.g. usual _calendars_ (<<term-calendar>>), where the time axis is split up into a succession of consecutive _time intervals_ (<<term-time-interval>>) and the same mark is attributed to all instants of each time interval;
* discrete, e.g. in digital techniques.
====
````

We can let that kind of error slide, but I wanted to bring that to your attention.

**Comment by opoudjis** [comment]
Individual definitions in definition lists are not meant to contain notes; notes are meant to be appended at the end of the whole definition list:

````
_c(x, y)_::
time scale component c extended to accept a fixed-point number, with x digits in the decimal part and y digits in the fractional part, such as [year(6,0)] represents a year time scale component that accepts 6 digits for year; [min(2,3)] represents a minute time scale component that accepts 2 digits in the decimal part and 3 digits in the fraction part, separated by a decimal sign
+ 
NOTE: If y is omitted it is assumed to be zero. Thus [year(6)] means the same as [year(6,0)].
````

Let me know if you want to allow notes inside individual definitions. I'd again rather we not relax things.

**Comment by ronaldtse** [comment]
@opoudjis Re: term note. It is something we have to support since the IEV terms allow it. Perhaps we should review the ISO 300XX termbase exchange standard for terms?

**Comment by ronaldtse** [comment]
Re: prefactory text in symbols / abbreviations. I understand that for abbreviations, but there is some explanation necessary for symbol sections?

**Comment by opoudjis** [comment]
We have not until now differentiated symbols and abbreviations; we have treated them as the same thing. The grammar does not permit any prefatory text in a terms and definitions section or its children. I'd rather it doesn't; any instances of such prefatory text anywhere need to be confirmed anyway, since they are not foreseen in the directive.

**Comment by opoudjis** [comment]
> It is something we have to support since the IEV terms allow it. Perhaps we should review the ISO 300XX termbase exchange standard for terms?

https://github.com/riboseinc/metanorma-model-iso/issues/38
