### ISSUE TITLE
Fail to render section header when anchor starts with digit

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/metanorma-iso#200]
```
[[24-hour-clock]]
==== The 24-hour clock

This document 
```

Output: `[[24-hour-clock]] === The 24-hour clock`, fails to render heading.

```
[[time-scale-24-hour-clock]]
==== The 24-hour clock

This document 
```

Works. The issue occurs when the anchor starts with a digit.

**Comment by opoudjis** [comment]
This is an Asciidoctor constraint, inherited from XML schema:

https://asciidoctor.org/docs/user-manual/#auto-generated-ids

> Refer to the [NT-Name](https://www.w3.org/TR/REC-xml/#NT-Name) section of the XML specification for a list of valid ID characters.

https://www.w3.org/TR/REC-xml/#NT-Name

> [Definition: A Name is an Nmtoken with a restricted set of initial characters.] Disallowed initial characters for Names include digits, diacritics, the full stop and the hyphen.

No, I will not document this in the guidelines, because we should not be replicating the contents of the Asciidoctor User Manual.
