### ISSUE TITLE
IEV references fail

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/metanorma-iso#202]
```
<IEV,clause 113-01-12>>
```

Now produces `-12`.

```
<IEV,clause 113.01.12>>
```

Now produces `clause 113-01-12`

**Comment by opoudjis** [comment]
https://github.com/riboseinc/metanorma-iso/blob/master/docs/guidance.adoc:

> By ISO convention, IEV references are not included in the bibliography, but for consistency and validation purposes, the IEV should be cited as a normal reference, with the term given as a clause, and the source should be named as IEV in the bibliography.

**Comment by opoudjis** [comment]
https://github.com/riboseinc/metanorma-iso/issues/206 is going to override a lot of this. For now:

The IEV references need to be in the format `<<IEV,clause "113-01-12">>`. That preserves the dashes in the eventual reference; and the reference type does need to be given explicitly for any locality.

I will fix the references in ISO 8601-1. Eventually by #206, they will be cited as IEC references.
