### ISSUE TITLE
Inline anchor references not making to HTML

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/metanorma-iso#203]
```adoc
. [[time-interval-start-end]]by a start and an end;
. [[time-interval-start-duration]]by a start and a duration;
. [[time-interval-duration-end]]by a duration and an end.

A solidus ["/"] shall be used as a separator to separate the two components in each of <<time-interval-start-end>>, <<time-interval-start-duration>> and <<time-interval-duration-end>>.
```

The references are rendered correctly, but the anchors are missing from the HTML (probably also the Word), i.e. you cannot "click and jump".

**Comment by opoudjis** [comment]
Isodoc rendering of HTML is ignoring anchors on `<li>`, which is where that anchor is ending up.

Fixed in isodoc; all lists and list children were having their anchors ignored.
