### ISSUE TITLE
Cover page issues

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/metanorma-iso#205]
1. It is now always "ISO [stage] ISO 1234" rather than "ISO [stage] 1234", even with this:

```
:ref-docnumber: 8601-1:2018(E)
```

2.
```
:technical-committee-type: TC
:technical-committee-number: 123
```

Generates `ISO  TC 123`. (there are 2 spaces before `TC`)

3. 
```
:secretariat: ABC
```

Generates `Secretariat : ABC`, it should be `Secretariat: ABC`.

**Comment by opoudjis** [comment]
3 is Word only issue. Header had a hyperlink around secretariat, and was inserting spurious space around it. Fixed.

**Comment by opoudjis** [comment]
2. Again, profusion of `<span>` elements inherited from Word ISO template, which are being pretty printed by Nokogiri—which inserts spurious space. Fixed.

**Comment by opoudjis** [comment]
1. Template was printing Agency separate from Document identifier, but document identifier now includes agency abbreviation. Need to ensure stage follows agency name, instead of preceding it.

**Comment by opoudjis** [comment]
Fixed document identifier
