### ISSUE TITLE
Citation of IEV styles in official manner

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/metanorma-iso#206]
I wrote to IEV to ask about the official citation style and got this response. We should support the official way of citing IEV entries for simplicity.

> In accordance with the ISO/IEC Directives, Part 2, the source of a repeated definition is a dated reference since you are referring to a specific numbered subdivision of text (and furthermore, you are using as your source a specific instance of an IEV entry).
 
> Thus although it would be much easier to cite [SOURCE: IEV 113-01-07] rather than [SOURCE: IEC 60050-113:2011, 113-01-07], IEV 113-01-07 is an undated reference, and as such it refers to the latest version of IEV 113-01-07 (which may change over time, and thus at one time instant this IEV entry may not correspond to the IEV entry that you used as a source).
 
> There are two ways you can use to refer to a specific instance (i.e. to make a dated reference) of an entry in the IEV:
 
> - by making a reference to the source publication, i.e. your less easy example [SOURCE: IEC 60050-113:2011, 113-01-07] - fyi, the IEC Supplement to the ISO/IEC Directives also mentions this style of reference in SK.3.1.3:
 
![image004](https://user-images.githubusercontent.com/11865/44204431-1a5fac00-a185-11e8-969e-b22ca8c889dc.png)
 
> - by referring to the IEV number followed by the publication date shown in Electropedia (it is at the bottom of the page http://www.electropedia.org/iev/iev.nsf/display?openform&ievref=113-01-07)
 
> [SOURCE: IEV 113-01-07:2011-04]
 
> but in this case you make the assumption that the user knows where to find IEV 113-01-07 and so, as mentioned in the ISO/IEC Directives, Part 2, 10.3, you would need to add "the method of access to the referenced document and the full network address" as well as the "viewed" date, e.g.
 
> [SOURCE: IEV 113-01-07 [viewed 20xx-xx-xx]. Available at: www.electropedia.org]
  
> So, at the end of the day you have the choice between

> [SOURCE: IEC 60050-113:2011, 113-01-07]
> or
> [SOURCE: IEV 113-01-07 [viewed 20xx-xx-xx]. Available at: www.electropedia.org]

**Comment by ronaldtse** [comment]
Official answer:

> The standard formulation used in all IEC documents is [SOURCE: IEC 60050-113:2011, 113-01-07]. Whilst [SOURCE: IEV 113-01-07:2011] plus an associated reference to Electropedia is not formally wrong, I am not enthusiastic in introducing deviations from our house style.

**Comment by opoudjis** [comment]
So the wording in our documentation,

> By ISO convention, IEV references are not included in the bibliography, but for consistency and validation purposes, the IEV should be cited as a normal reference, with the term given as a clause, and the source should be named as IEV in the bibliography.

needs to change, right? The IEV is not being conventionally cited, it is being explicitly cited as IEC 60050-x for each subject area. I will automatically need to convert IEV to each IEC reference.

**Comment by ronaldtse** [comment]
And here's officially why we can't directly create a citation from the IEV term page.

> For example: http://www.electropedia.org/iev/iev.nsf/display?openform&ievref=113-01-17
 
> I can infer the Part number as “113”
>> Yes
 
> and the edition date “2011”.
>> No. Without checking in the IEC list of publications, you don't know whether 2011 is the publication date of the standard or an amendment.

**Comment by opoudjis** [comment]
The work is almost done, but I cannot use isobib to query the latest version of IEC 60050-nnn, because isobib does not query the www.iec.ch website at all. As a matter of urgency, isobib needs to be extended to search and parse www.iec.ch for standards starting with "IEC".

**Comment by opoudjis** [comment]
Because I can't wait two weeks, I'm going to create dummy IEC 60050-nnn entries in isobib, all with a date of 2011. When we have true IEC retrieval in isobib (or iecbib, but I would prefer we not needlessly proliferate gems), I will switch across to it.

**Comment by opoudjis** [comment]
I have switched IEV and IEC-60050 retrieval to iecbib.

Have altereed metanorma-standoc to fetch and enforce the year of publication of the specific IEC-60050 standards.

**Comment by opoudjis** [comment]
Fixed in Metanorma-standoc

**Comment by ronaldtse** [comment]
Thanks @opoudjis!
