### ISSUE TITLE
Validate that term mention in T&D is italicised

### ISSUE THREAD

**Issue by opoudjis** [riboseinc/metanorma-iso#210]
Any term in a term definition that precedes a term crossreference.

**Comment by ronaldtse** [comment]
@oppudjis can we have a list of these validation rules in the README/website as documentation, and also in code a list of these rules so that we can easily add / remove and in the future enable / disable them? Maybe that’s a new ticket.

**Comment by opoudjis** [comment]
Other than this, they are all rules from ISO/IEC DIR 2. https://github.com/riboseinc/metanorma-iso#content-warnings lists the content rules already; I assume this generalises to all structural warnings, and that it becomes a separate document.
