### ISSUE TITLE
doc version looks not right

### ISSUE THREAD

**Issue by wsdwl** [riboseinc/metanorma-iso#219]
When creating the document from https://github.com/CalConnect/VCARD/tree/master/csd/datetime-explicit, all files are created.

As the *.doc document still can be opened using MS Word, it looks like a multipart mixed format which prevents it from being opened in other programms

`MIME-Version: 1.0
Content-Type: multipart/related; boundary="----=_NextPart_8d0d8439.2aa7.4856"

------=_NextPart_8d0d8439.2aa7.4856
Content-Location: file:///C:/Doc/csd-datetime-explicit.htm
Content-Type: text/html; charset="utf-8"

<?xml version="1.0"?>
<html xmlns:epub="http://www.idpf.org/2007/ops" xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:w="urn:schemas-microsoft-com:office:word" xmlns:v="urn:schemas-microsoft-com:vml" xmlns:m="http://schemas.microsoft.com/office/2004/12/omml" xmlns="http://www.w3.org/TR/REC-html40">
  <head><!--[if gte mso 9]>
<xml>
<w:WordDocument>
<w:View>Print</w:View>
<w:Zoom>100</w:Zoom>
<w:DoNotOptimizeForBrowser/>
</w:WordDocument>
</xml>
`
...

`------=_NextPart_8d0d8439.2aa7.4856
Content-Location: file:///C:/Doc/csd-datetime-explicit_files/filelist.xml
Content-Transfer-Encoding: base64
Content-Type: application/xml

PHhtbCB4bWxuczpvPSJ1cm46c2NoZW1hcy1taWNyb3NvZnQtY29tOm9mZmljZTpvZmZpY2UiPgog
ICAgICAgIDxvOk1haW5GaWxlIEhSZWY9Ii4uL2NzZC1kYXRldGltZS1leHBsaWNpdC5odG0iLz4g
IDxvOkZpbGUgSFJlZj0iZmlsZWxpc3QueG1sIi8+CiAgPG86RmlsZSBIUmVmPSJoZWFkZXIuaHRt
bCIvPgo8L3htbD4K

------=_NextPart_8d0d8439.2aa7.4856
Content-Location: file:///C:/Doc/csd-datetime-explicit_files/header.html
Content-Transfer-Encoding: base64
Content-Type: text/html charset="utf-8"

PGh0bWwgeG1sbnM6dj0idXJuOnNjaGVtYXMtbWljcm9zb2Z0LWNvbTp2bWwiDQp4bWxuczpvPSJ1
cm46c2NoZW1hcy1taWNyb3NvZnQtY29tOm9mZmljZTpvZmZpY2UiDQp4bWxuczp3PSJ1cm46c2No
ZW1hcy1taWNyb3NvZnQtY29tOm9mZmljZTp3b3JkIg0KeG1sbnM6bT0iaHR0cDovL3NjaGVtYXMu
bWljcm9zb2Z0LmNvbS9vZmZpY2UvMjAwNC8xMi9vbW1sIg0KeG1sbnM6bXY9Imh0dHA6Ly9tYWNW
bWxTY2hlbWFVcmkiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy9UUi9SRUMtaHRtbDQwIj4NCg0K
PGhlYWQ+DQo8bWV0YSBuYW1lPVRpdGxlIGNvbnRlbnQ9IiI+DQo8bWV0YSBuYW1lPUtleXdvcmRz`

...

`L3NwYW4+PC9wPg0KDQo8L2Rpdj4NCg0KPC9ib2R5Pg0KDQo8L2h0bWw+DQo=

------=_NextPart_8d0d8439.2aa7.4856--

`

**Comment by opoudjis** [comment]
We've discussed why we are using Doc (= MHT) rather than DOCX here: https://github.com/riboseinc/html2doc/wiki/Why-not-docx%3F

**Comment by ronaldtse** [comment]
@wsdwl we're closing this ticket in favor of better documentation on Word output. Basically, if one needs Word output, one needs a real install of Microsoft Word.

Which I think is fair enough -- if you don't have Word, how do you verify that the output is proper?

The output we provide here is "real" Word, not OpenOffice XML ("fake Word") understood by Pages or LibreOffice.

**Comment by ronaldtse** [comment]
Superceded by #220

**Comment by opoudjis** [comment]
> The output we provide here is "real" Word, not OpenOffice XML ("fake Word") understood by Pages or LibreOffice.

Actually, the output we provide is both legacy Word (DOC = MHT). Real current Word output *is* (zipped) OOXML; but generating the OOXML to do what we need, with the full range  of functionality we need, is a massive undertaking we are not taking on for now.

**Comment by ronaldtse** [comment]
Clarified the above comment. Thanks.
