### ISSUE TITLE
"Symbol and abbreviated terms" is used as clause header even when both clauses are separate

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/metanorma-iso#222]
Under a structure like this:

```
== Terms, definitions, symbols and abbreviated terms

=== Terms and definitions

=== Symbols       => This renders as "Symbols and abbreviated terms"

=== Abbreviated terms   => This also renders as "Symbols and abbreviated terms"

```

The last two should not have the same heading.

**Comment by ronaldtse** [comment]
This occurs in 8601-1.

**Comment by ronaldtse** [comment]
All I can say is that this structure is accepted by ISO/CS; I don't know if it's an abuse or not.

**Comment by ronaldtse** [comment]
I wonder if it's better to convert this "strict" title into a warning; if even I being so tightly familiar with the toolchain, runs into this issue, other definitely will.

**Comment by opoudjis** [comment]
Respecting title of Definitions sections, whatever it might be. (Note that unless the "heading" attribute is used, only Symbols, Abbreviated Terms, and Symbols & Abbreviated Terms will be recognised.) Propagating title to definitions section in grammar. Modifying metanorma-standoc and isodoc to respect title of Definitions section.
