### ISSUE TITLE
Word Annex clause headers must be bolded

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/metanorma-iso#223]
Currently:

<img width="514" alt="screen shot 2018-10-05 at 8 40 15 am" src="https://user-images.githubusercontent.com/11865/46510252-5c9a9500-c87a-11e8-99db-99b4d7b19138.png">

All Annex headers should be bolded just like normal headers.

**Comment by ronaldtse** [comment]
"A.1.1." is bolded but "A.1." is not.

**Comment by opoudjis** [comment]
Annex subheadings are in the special style h2Annex in Word; need to ensure that style is still in all the stylesheets.

**Comment by opoudjis** [comment]
Bizarreness of Word CSS: I told it h2Annex uses Heading 2 Char, but it still had to be told explicitly that the style is boldface; the corresponding h2 definition does not need the explicit notation. Fixing all h2Annex instances.
