### ISSUE TITLE
Stray "NOTE 3" in 8601-2 document

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/metanorma-iso#224]
In clause 5.2, the sole "NOTE" element is numbered as "NOTE 3". I suspect there must be some counter doing something wrong.

**Comment by opoudjis** [comment]
No, there are two notes embedded in definition list after the formula, which are not being rendered. They should not be being embedded, but if they are being embedded, they should be rendered.

Crap.

Debugging both issues.

**Comment by opoudjis** [comment]
Pushing extraneous content (including notes) through in formula in isodoc.

**Comment by opoudjis** [comment]
The grammar does license notes at the end of formulas, so this is an isodoc omission.
