### ISSUE TITLE
Included image should span whole width of Word, but not beyond

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/metanorma-iso#225]
Currently including an image of a larger size ends up requiring manual adjustment:

<img width="746" alt="screen shot 2018-10-05 at 9 02 16 am" src="https://user-images.githubusercontent.com/11865/46510761-7c7f8800-c87d-11e8-8d1c-4e8a6994d6b0.png">

**Comment by opoudjis** [comment]
Had transposed max width and max height in html2doc.
