### ISSUE TITLE
Metanorma XML should be able to store math in MathML format

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/metanorma-iso#229]
Currently Metanorma XML math is stuck to AsciiMath, which is not in XML and does not have a proper schema.

Storing math in AsciiMath is like storing text in AsciiDoc.

Metanorma XML should support storing math in MathML. (i.e. move Asciimath processing to prior generation of Metanorma XML)

**Comment by ronaldtse** [comment]
Change: Metanorma XML should by default use MathML instead of AsciiMath.

**Comment by opoudjis** [comment]
Adding the metanorma-cli option `-a, --asciimath`, and the metanorma Asciidoctor directive `:mn-keep-asciimath:`. By default, they will be disabled.

**Comment by opoudjis** [comment]
Implemented in metanorma-standoc, metanorma, metanorma-cli
