### ISSUE TITLE
Support ISO submission conventions on draft output

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/metanorma-iso#230]
1. "ICS XXX" and "Pricing based on pages" is only for "published" documents

2. Allow adding a TC "N" number (the document number amongst the TC documents) (whatever stage it is)

3. Show rev date of draft (if it's a draft)

4. Change "ISO FDIS" to "ISO/FDIS", "ISO TC 154" to "ISO/TC 154"

See below.

<img width="629" alt="screen shot 2018-10-06 at 8 40 15 pm" src="https://user-images.githubusercontent.com/11865/46571466-0fb4dc80-c9a8-11e8-8d79-4ca8dddd3a66.png">

**Comment by opoudjis** [comment]
1. The only way to do that currently is to suppress the entire colophon if the document is in draft; but that's fine, the colophon is clearly the attribute of a published document anyway. Done.

**Comment by opoudjis** [comment]
4. Done.

3. Done.

**Comment by ronaldtse** [comment]
2. Will work as you described. I’ve sent you another document privately to demonstrate. 

If it’s a distributed draft, it will have a “TC/SC/WG N number”.

In the draft I sent you, it even has two “N numbers”, one for the SC and one for the WG.

I think for the N number, we should let the user specify the N number scope and the number itself him/herself. For example, it could be “ISO/TC 154/WG 5” “123” or “ISO/TC 154”, “1234”. 

I actually realized that the screenshotted document had an error: the 4th line should say the authoring unit, which is “ISO/TC 154/WG 5”.

**Comment by opoudjis** [comment]
1. You sent me a draft? I have no email notification of it.

2. TWO N NUMBERS?!

ISO is not making this up as they're going along, but that's the impression I'm getting. Right now, there is provision for a tc-document-number. If that is not what is going on, I am not interested in composing numbers that are not specified properly. 

So until I hear different, I am putting whatever is in the  tc-document-number field up in the top corner. The onus will be on the user to prefix it with the TC name, the WC name, to concatenate the two N numbers, or whatever else is going on. This seems to be what you are saying. 

3. I am assuming this is a concatenation of TC/SC/WG as those identifiers are available.

There have to be formal specifications of these identifiers. I need to have access to them.

**Comment by opoudjis** [comment]
The fact that published documents have no trace of the TC/SC/WG N number tells me that there is more about these document identifiers I need to know about. In a formal specification.

**Comment by opoudjis** [comment]
It looks like I'd already implemented the concatenation of editorial groups, as in `ISO/TC 154/WG 5`. 

This is what the gem currently does:

````
= Document title
Author
:docfile: test.adoc
:novalid:
:data-uri-image:
:docnumber: 123
:tc-docnumber: ISO/TC 33/456
:revdate: 2011-01-01
:technical-committee-number: 33
:technical-committee: Bolts
:docstage: 50
:workgroup-number: 89
:subcommittee-number: 10
````

As warned, I've declined currently from putting any smarts into `tc-docnumber`. The output currently is:

> *ISO/TC 33/456* 
> Date: 2011-01-01 
> ISO/FDIS 123:2018(E) 
> ISO/TC 33/SC 10/WG 89 
> Secretariat: XXXX 

Leaving the ticket open for you to confirm this is acceptable, @ronaldtse. The gem doesn't work right now with the relaton fail.

**Comment by ronaldtse** [comment]
I think multiple N numbers only mean that there can be multiple document identifiers per document, which makes sense.

**Comment by opoudjis** [comment]
but if they have different editorial group prefixes, and they are all meant to be rendered in the one string, I have no easy way of automatically doing that. That's why leaving the target string as is in the document attribute is easier for everybody.

**Comment by ronaldtse** [comment]
I don't mean we should render it all in one string, so there's nothing further to be done here.

However, I want to confirm that the Relaton model supports multiple document identifiers (i.e. "scope" + ID within scope). Thanks!

**Comment by opoudjis** [comment]
````
BibliographicItem =
    attribute type { BibItemType }?,
    fetched?,
    (btitle+ | formattedref), bsource*, docidentifier*, ....

docidentifier = element docidentifier {
  attribute type { text }?,
  text
}
````
