### ISSUE TITLE
List spacing

### ISSUE THREAD

**Issue by opoudjis** [riboseinc/metanorma-iso#231]
Now that there is no list container, Word CSS has no good way of guaranteeing the same space after a list as after a paragraph. I have put margin-bottom:12pt on p.MsoListParagraphCxSpLast in the ISO stylesheet, but it is being ignored. Even if it were not, it would lead to unsightly gaps in nested lists.

Word CSS seems to have been hardcoded to expect space above and beyond list items.

**Comment by opoudjis** [comment]
Check against ISO template for native list styles in Word CSS: https://www.iso.org/iso-templates.html

**Comment by opoudjis** [comment]
Template does not include native Word list styles; but it does have space after all list items.

**Comment by ronaldtse** [comment]
Great find, at least we know the right direction.

**Comment by opoudjis** [comment]
It turns out that the Word CSS command "mso-add-space:auto", which is on in Word by default, will make lists compact: there is space before or after a list item, but space between list items, regardless of their respective depths, is eliminated.

This looks nice. OTOH, it is not the behaviour of the ISO template. So I am enabling it for all stylesheets but ISO and GB: for those two, there will always be 12pt of space after each list item.

**Comment by opoudjis** [comment]
Also, need to force lists embedded within examples to be of the same font size as the example paragraphs (which is smaller).

**Comment by opoudjis** [comment]
Done. Note that the native positional styles, p.MsoListParagraphCxSpFirst p.MsoListParagraphCxSpMiddle p.MsoListParagraphCxSpLast, seem to be ignored, even though that is what is in the document: the class Word actually pays attention to is p.MsoListParagraph.

**Comment by ronaldtse** [comment]
For GB we can apply the nicer fix too. They are not linked to the ISO template.

**Comment by opoudjis** [comment]
Done
