### ISSUE TITLE
Refactor document identifier

### ISSUE THREAD

**Issue by opoudjis** [riboseinc/metanorma-iso#237]
There is an issue is about docidentifier.

In the iso version docidentifier is more refined

Either we do that for other standards, or give another ID called “fullid” that incorporates every element

**Comment by opoudjis** [comment]
Decision: will add document-number element distinct from document-identifier to relaton XML, which will contain the number-only component of the document identifier, and will be used for sorting.

The document-identifier proper shall be a full identifier, containing a single atomic string. Any downstream processes will need to treat it accordingly, which means that metanorma-iso/isodoc will need to do so.

**Comment by ronaldtse** [comment]
@opoudjis , do you realize that the current ISO document cover page has a broken doc id?

See the Rice doc (HTML and Word):
<img width="225" alt="screen shot 2018-11-08 at 2 33 34 am" src="https://user-images.githubusercontent.com/11865/48184025-b3beda00-e2fe-11e8-8150-2c575580b49c.png">

The document identifier should contain the "ISO" prefix and stage codes.

**Comment by opoudjis** [comment]
No I did not realise it. As I keep telling you, I can no longer keep up.

**Comment by opoudjis** [comment]
* Adding document-number as optional element to relaton, containing the numeric/identifying element of the identifier, without prefixes indicating the document standard class, or suffixes indicating date or status.
* Including document-number in metanorma-standoc output.
* Ensuring that all downstream gems from metanorma-standoc output both document-number and document-identifier.
* Ensuring that document-identifier is populated in asciidoctor subdirectory, as a full string
* Ensuring that all sample documents are populated with document-identifier on their front page

**Comment by opoudjis** [comment]
Retaining the old structured format of document identifiers under a *-structured type; e.g.

````
  <docidentifier type="iso">ISO 17301-1:2016</docidentifier>
  <docidentifier type="iso-structured">
    <project-number part="1">ISO 17301</project-number>
  </docidentifier>
  <docidentifier type="iso-tc">17301</docidentifier>
  <docnumber>17301</docnumber>
````
