### ISSUE TITLE
No spacing after EXAMPLEs and Tables

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/metanorma-iso#242]
The current formatting gives no spacing after examples (and Tables!) making the next paragraph seemingly belonging to the above example.

**Comment by opoudjis** [comment]
This was supposed to have been resolved in https://github.com/riboseinc/metanorma-iso/issues/234. Checking.

**Comment by opoudjis** [comment]
It turns out that Word HTML requires the frame Word CSS commands to be inline in the table, and will not process them from the stylesheet. In fact, they need to be *deleted* from the stylesheet.

**Comment by opoudjis** [comment]
Fixed in isodoc, gem stylesheets

**Comment by opoudjis** [comment]
The large mso-table-rspace, mso-table-lspace are from https://superuser.com/questions/728099/how-can-i-add-spacing-between-a-table-and-the-paragraph-immediately-after-it#comment1353888_728303
