### ISSUE TITLE
Single quotes being very strange (close quotes x 2?)

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/metanorma-iso#246]
See below. Both are entirely identical in encoding. Maybe the "smart quotes" are getting too "smart".

Example 1.

<img width="312" alt="screen shot 2018-12-31 at 1 50 48 am" src="https://user-images.githubusercontent.com/11865/50549819-9246f280-0c9e-11e9-8e3e-ce953177941f.png">

Example 2.

<img width="409" alt="screen shot 2018-12-31 at 1 51 05 am" src="https://user-images.githubusercontent.com/11865/50549820-996e0080-0c9e-11e9-8ec5-216ce10605cb.png">

P.S. This is from the 8601-1 document, all pushed.

**Comment by opoudjis** [comment]
This is a problem with the sterile gem: it thinks '12 is the year 1912, which should be ’12. That is actually true, but not when there is a closing quote.

I'm going to request a fix, but the gem has not been updated in 2 years; just in case, I'm going to fork it to us.

**Comment by opoudjis** [comment]
Pull request created. I'm somewhat inexpert in creating local gem instances for use in the stack: I've been able to get Gemfile to pull local instances of gems, but have not had success with inheritance. We will need to use our instance of sterile, and the current instance on github of asciimath, until there is a release.

**Comment by opoudjis** [comment]
Keep this ticket open until either sterile is released, or we take it over if it is inactive.

**Comment by opoudjis** [comment]
Pull Gemfile for 8601-1 and 8601-2 to obtain correct behaviour for quotes.

**Comment by ronaldtse** [comment]
Whoh. Hope this gets merged soon. Maintaining a custom forked fix isn't making the toolchain easy to use 😉

**Comment by ronaldtse** [comment]
Until the fix gets merged, can you include this file inside StanDoc? e.g. in a directory called `lib/hacks/sterile.rb`?

https://github.com/pbhogan/sterile/blob/b70c0f0aac15eee5f6667c98915d4ab075042869/lib/sterile/data/smart_format_rules.rb

You will need to `require "lib/hacks/sterile` after `require "sterile"` in `lib/metanorma/standoc.rb` so that your hack overrides the original one.

Then we don't need the end-user to use our fork.

(similarly, with Asciimath)

**Comment by opoudjis** [comment]
Oh! I didn't realise you could do that! OK.

**Comment by opoudjis** [comment]
Workaround in place, keeping ticket open until we know status of sterile.

**Comment by opoudjis** [comment]
Sterile has been updated.

**Comment by opoudjis** [comment]
Yes

**Comment by ronaldtse** [comment]
Thanks!
