### ISSUE TITLE
Broken EXAMPLE table rendering in Word

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/metanorma-iso#249]
Uggg.... the EXAMPLE went off the page... Need fix + version bump...

![screen shot 2019-01-23 at 12 37 45 am](https://user-images.githubusercontent.com/11865/51550351-29225b80-1ea7-11e9-8480-0ff68d02853d.png)

**Comment by opoudjis** [comment]
I cannot replicate:

<img width="959" alt="image" src="https://user-images.githubusercontent.com/1911039/51555095-bc8b6a80-1e6e-11e9-8713-9c5c855c84f1.png">

**Comment by opoudjis** [comment]
Could you confirm the versions of isodoc and metanorma-iso that you're using? This is what I got when running bundle update.

````
Using isodoc 0.9.15 (was 0.9.14)
Using isobib 0.4.3
Using relaton 0.3.1
Using metanorma-standoc 1.1.1 (was 1.0.14)
Using metanorma-acme 1.1.0 (was 1.0.9)
Using metanorma-csand 1.1.0 (was 1.0.12)
Using metanorma-csd 1.1.0 (was 1.0.14)
Using metanorma-iso 1.1.0 (was 1.0.13)
Using metanorma-ietf 1.0.1 (was 1.0.0)
Using metanorma-m3d 1.1.0 (was 1.0.13)
Using metanorma-mpfd 0.1.6 (was 0.1.5)
Using metanorma-nist 0.0.2 (was 0.0.1)
Using metanorma-ogc 0.0.4 (was 0.0.3)
Using metanorma-rsd 1.1.0 (was 1.0.13)
Using metanorma-unece 0.0.9 (was 0.0.8)
Using metanorma-gb 1.1.0 (was 1.0.12)
Using metanorma-cli 1.1.3 (was 1.1.2)
````

**Comment by opoudjis** [comment]
... In fact, this shouldn't be happening at all: the whole point is that ISO does *not* use div rendering for its examples, but the existing table rendering. If you're going to see a problem, it should be in non-ISO/GB documents.

**Comment by opoudjis** [comment]
I'm regenerating as CSD not ISO. That uses the new div rendering of examples, but it's still not coming up with any problems:

<img width="955" alt="image" src="https://user-images.githubusercontent.com/1911039/51555426-7d114e00-1e6f-11e9-8619-32287c0382df.png">

**Comment by opoudjis** [comment]
Issue turned out to be Ronald's bundle was fetching obsolete version of metanorma-iso gem
