### ISSUE TITLE
Handling of non-term sections inside T&D

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/metanorma-iso#251]
In previous versions, we did not have to mark `[.nonterm]` sections. 

Now, we need to mark `[.nonterm]` sections on every section that is non-term. Yet this is also confusing -- I needed to mark `[.nonterm]` for the sections with definition lists such as "Symbols", "Abbreviations" because otherwise the styling will be off.

Without the `[.nonterm]` marking, I get these:

<img width="481" alt="screen shot 2019-01-29 at 4 53 43 pm" src="https://user-images.githubusercontent.com/11865/51912753-fe3c8800-240f-11e9-9a03-4e074d7fceb9.png">

<img width="275" alt="screen shot 2019-01-29 at 4 53 48 pm" src="https://user-images.githubusercontent.com/11865/51912752-fda3f180-240f-11e9-88d5-448a19dd7079.png">

And the `[.nonterm]` marking is not inherited -- I cannot specify a `[.nonterm]` at 3.2. I must specify the `[.nonterm]` in every single section: 3.2.1, 3.2.2, 3.2.3, etc.

However, this might actually be the desired behavior, because we don't have types.

The other solution is to mark every "term" as a `[term]`, but it may be too much to expect?

**Comment by opoudjis** [comment]
The other solution is a very bad idea: nonterm is the exception, not the rule. I think it is fair though to stipulate that nonterm should only be tagged on a leaf node, and if a subsection of `<terms>` contains children, that should automatically make it be treated as a nonterm. That is a simple code change, which I will do on this ticket.

**Comment by opoudjis** [comment]
And the styling of definitions should be autonomous of the styling of terms anyway.

I do not understand the problem you are raising here with inheritance. I have tested the following, and the behaviour is exactly what I would expect:

````
== Terms, Definitions, Symbols and Abbreviated Terms

[.nonterm]
=== Introduction

==== Intro 1

=== Intro 2

[.nonterm]
==== Intro 3

=== Intro 4

==== Intro 5

===== Term1

=== Normal Terms

==== Term2

````

converts  to:

````
<clause id="_" obligation="normative"><title>Terms, definitions, symbols and abbreviated terms</title><clause id="_" inline-header="false" obligation="normative">   
  <title>Introduction</title>   
  <clause id="_" inline-header="false" obligation="normative">    
  <title>Intro 1</title>    
</clause>   
</clause>  
<terms id="_" obligation="normative">   
  <title>Intro 2</title>   
  <clause id="_" inline-header="false" obligation="normative">    
  <title>Intro 3</title>    
</clause>   
</terms>  
<clause id="_" obligation="normative">   
  <title>Intro 4</title>   
  <terms id="_" obligation="normative">    
  <title>Intro 5</title>    
  <term id="_">     
  <preferred>Term1</preferred>     
</term>    
</terms>   
</clause>  
<terms id="_" obligation="normative">   
  <title>Normal Terms</title>   
  <term id="_">    
  <preferred>Term2</preferred>    
</term>   
</terms>  
````

In particular: Intro1 is a clause, inheriting that characteristic from the nonterm clause Introduction. 

You will have to be a lot clearer about what your expected behaviour is, with actual examples.

**Comment by opoudjis** [comment]
I see what the styling issue is: whether the clause number is on a separate line from the clause title. Please be more explicit about this kind of question.

That is a styling issue: whether the number is on a separate line or not should only be determined by whether the clause is a term or not, and it must not be applied to definitions subclauses of terms & definitions sections, no matter what the hierarchical nesting.

**Comment by opoudjis** [comment]
The issue is in fact that the children of a definitions subsection are by default terms. That is wrong, fixing.

**Comment by opoudjis** [comment]
Fixed: definitions children now being processed correctly as definitions, not terms.

This has now raised the issue seen in https://github.com/riboseinc/isodoc/issues/85: notes within nested definitions are no longer being found for labelling.

**Comment by opoudjis** [comment]
With these issues resolved, the nonterm styling of the definitions subclauses is no longer needed. Checking in 8601-1 without the nonterms.
