### ISSUE TITLE
Question about AsciiISO

### ISSUE THREAD

**Issue by strogonoff** [riboseinc/metanorma-iso#252]
@opoudjis is probably best-positioned to answer this but I’ll cc @ronaldtse too just in case.

While consolidating flavour-specific markup docs under [in case of Metanorma-ISO] www.metanorma.com/flavours/iso/markup/, I’m taking the available sources as reference. They are:

* Authoring guidance @ [GitHub](https://github.com/riboseinc/metanorma-iso/blob/master/docs/guidance.adoc)/[Metanorma.com](http://metanorma.com:4001/software/metanorma-iso/docs/guidance/)
* Asciidoctor additions @ [Metanorma-ISO README](https://github.com/riboseinc/metanorma-iso#asciidoctor-model-additions)
* AsciiISO syntax reference @ [Metanorma.com](http://www.metanorma.com/software/metanorma-iso/docs/asciiiso-syntax/) (but under “ISO specific syntax”, it only links to README and Guidance)

Could you help me understand if I can take one of them as a source for all **ISO-specific** matters (including, if applicable, any particular ways of using the built-in Asciidoctor elements, e.g. if some of them mandatory under ISO)—and if so which one would it be?

**Comment by opoudjis** [comment]
The ISO specific guidance is contained in the metanorma-iso readme. The Authoring guidance and AsciiISO syntax reference are intended to be applicable across all Metanorma flavours, with annotations for standards-specific markup and conventions; but the authoritative source for standards-specific documentation remains the readmes.
