### ISSUE TITLE
EXAMPLEs are just like NOTES -- not tables!

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/metanorma-iso#256]
@opoudjis this is counter to previous experience, but reflects current (2019!) practice.

EXAMPLEs are now just treated like NOTEs, they are not tables.

From Metanorma Word:

![screen shot 2019-02-13 at 4 25 17 pm](https://user-images.githubusercontent.com/11865/52697303-25688d00-2fac-11e9-92e4-9b5577bc657e.png)

From final publication PDF:

![screen shot 2019-02-13 at 4 26 19 pm](https://user-images.githubusercontent.com/11865/52697282-1a156180-2fac-11e9-99b8-f5f67188d42b.png)

**Comment by ronaldtse** [comment]
For completeness here is how EXAMPLEs and NOTEs interact.

Metanorma Word:

![screen shot 2019-02-13 at 4 30 45 pm](https://user-images.githubusercontent.com/11865/52697597-b7709580-2fac-11e9-81f6-d16ab1eb149b.png)

ISO PDF:

![screen shot 2019-02-13 at 4 30 23 pm](https://user-images.githubusercontent.com/11865/52697563-aa53a680-2fac-11e9-9b54-f6e28494e04e.png)

**Comment by opoudjis** [comment]
I will not touch this until we have official confirmation from the ISO secretariat that this is going to be the formatting henceforth. I will not jump at shadows.

**Comment by ronaldtse** [comment]
True. This is from an official ISO final proof. Let me double confirm.

**Comment by ronaldtse** [comment]
100% confirmed by ISO/CS. EXAMPLEs are NEVER tables.

**Comment by opoudjis** [comment]
As I've found, I switched example rendering to tables because that was the rendering used for ISO 690. But ISO 690 is a very old document.

**Comment by ronaldtse** [comment]
Thanks, in summary, ISO/CS confirmed that EXAMPLEs are now treated just like NOTEs, so this makes our lives easier.
