### ISSUE TITLE
Clause numbers should not be followed by a period

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/metanorma-iso#257]
From Metanorma:

![screen shot 2019-02-13 at 4 28 40 pm](https://user-images.githubusercontent.com/11865/52697450-72e4fa00-2fac-11e9-8b3d-79f64024d34c.png)

![screen shot 2019-02-13 at 4 27 36 pm](https://user-images.githubusercontent.com/11865/52697373-49c46980-2fac-11e9-93f7-5f9c1c1929b9.png)

From ISO final publication:

![screen shot 2019-02-13 at 4 28 37 pm](https://user-images.githubusercontent.com/11865/52697471-7d06f880-2fac-11e9-9fdf-998f6e791095.png)

![screen shot 2019-02-13 at 4 27 34 pm](https://user-images.githubusercontent.com/11865/52697377-4cbf5a00-2fac-11e9-9ba1-f901fe48264e.png)

**Comment by ronaldtse** [comment]
Confirmed with ISO/CS.

**Comment by opoudjis** [comment]
Parameterised clausedelim as a configurable function. Changed isodoc so that term numbers have the same behaviour as true clause numbers: either both end in a period, or neither.

**Comment by ronaldtse** [comment]
@opoudjis are the clause numbers generated by isodoc, or are the clause numbers (i.e. clause number format) written to the XML?

Considerations:
- We want to be able to address a particular clause via "clause number" via XML. If I put "5.1" vs "5.1.", should I find the same one? Or not?
- Different standards may or may not want the delimiter at the end.
- Different standards may use a different delimiter character.

**Comment by opoudjis** [comment]
Generated by isodoc. 

If you put in a number instead of a GUID to reference a clause number within the XML, you are simply doing it wrong. In any case, 5.1 simply does not currently appear in any XML.

ISO and isodoc have just implemented different behaviour for delimiter char.

**Comment by ronaldtse** [comment]
Thank you. You must know I’m very happy about this :wink:
