### ISSUE TITLE
In-clause EXAMPLE numbering missing

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/metanorma-iso#258]
Metanorma Word:

![screen shot 2019-02-13 at 4 32 42 pm](https://user-images.githubusercontent.com/11865/52697708-fe5e8b00-2fac-11e9-9b6a-048cf48025d0.png)

ISO PDF:

![screen shot 2019-02-13 at 4 32 33 pm](https://user-images.githubusercontent.com/11865/52697698-f868aa00-2fac-11e9-8118-5bd320366a9a.png)

**Comment by opoudjis** [comment]
Has been fixed in https://github.com/riboseinc/isodoc/issues/85
