### ISSUE TITLE
NOTE in definition list should be "NOTE" not "NOTE:"

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/metanorma-iso#260]
ISO PDF:

![screen shot 2019-02-13 at 4 35 44 pm](https://user-images.githubusercontent.com/11865/52697910-6a40f380-2fad-11e9-8d51-d1dec666cb45.png)

Metanorma Word:

![screen shot 2019-02-13 at 4 35 52 pm](https://user-images.githubusercontent.com/11865/52697924-6f05a780-2fad-11e9-9553-16a35d2633b4.png)

**Comment by ronaldtse** [comment]
(It seems that this issue only occurs for NOTEs inside definition lists?)

**Comment by ronaldtse** [comment]
I feel that maybe this "NOTE" was implemented not as a "NOTE" but actually as plain text...

**Comment by opoudjis** [comment]
Issue no longer present. `NOTE:` markup in Asciidoctor was clearly being ignored before, and no longer is. May have been fixed in https://github.com/riboseinc/isodoc/issues/85
