### ISSUE TITLE
ICS with codes and text

### ISSUE THREAD

**Issue by andrew2net** [riboseinc/metanorma-iso#37]
@opoudjis in https://github.com/riboseinc/gbbib/issues/9#issuecomment-395239458 Ronald ask to pace ICS code with text. But in grammars, we have only one field to place:
```
  <define name="ics">
    <element name="ics">
      <text/>
    </element>
  </define>
```
could we change the grammar to something like:
```
  <define name="ics">
    <element name="ics">
      <element name="code">
        <text/>
      </element>
      <element name="text">
        <text/>
      </element>
    </element>
  </define>
```
and do the smae with CCS?

**Comment by andrew2net** [comment]
@opoudjis Nick are you around?

**Comment by opoudjis** [comment]
I am now.

Sure, implementing.

**Comment by opoudjis** [comment]
Done, and pushed to asciidoctor-iso and asciidoctor-gb.

**Comment by andrew2net** [comment]
@opoudjis I don't see changes in asciidoctor-gb

**Comment by opoudjis** [comment]
!!

Maybe I clicked too slow; this is the commit:

https://github.com/riboseinc/asciidoctor-gb/commit/504798ef93d1b57ca5089e0478ef8925ae2cceb0

**Comment by andrew2net** [comment]
@opoudjis oh... I mean to change CCS in asciidoctor-gb
```
  <define name="gbccs">
    <element name="ccs">
      <element name="code">
        <text/>
      </element>
      <element name="text">
        <text/>
      </element>
    </element>
  </define>
```

**Comment by opoudjis** [comment]
Done
